""""create_all_tables"

Revision ID: 0bfb9897a4e6
Revises: 899a5a0675d5
Create Date: 2025-11-07 20:58:41.233964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bfb9897a4e6'
down_revision: Union[str, None] = '899a5a0675d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_export_batches_batch_type'), 'export_batches', ['batch_type'], unique=False)
    op.create_index(op.f('ix_export_batches_checksum'), 'export_batches', ['checksum'], unique=False)
    op.create_index(op.f('ix_export_batches_status'), 'export_batches', ['status'], unique=False)
    op.create_table('exportable_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_exportable', sa.Boolean(), nullable=True),
    sa.Column('transform_function', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('requires_encryption', sa.Boolean(), nullable=True),
    sa.Column('encryption_key_name', sa.String(), nullable=True),
    sa.Column('export_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_import_batches_batch_type'), 'import_batches', ['batch_type'], unique=False)
    op.create_index(op.f('ix_import_batches_checksum'), 'import_batches', ['checksum'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_request_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_request_limit', sa.Integer(), nullable=False),
    sa.Column('max_results_per_request', sa.Integer(), nullable=False),
    sa.Column('allowed_indices', sa.JSON(), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('request_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_type', sa.String(length=50), nullable=False, comment='نوع جستجوی الستیک\u200cسرچ (match, term, etc.)'),
    sa.Column('query_type_alias', sa.String(length=50), nullable=False, comment='نام مستعار برای نوع جستجو که به کاربران نمایش داده می\u200cشود'),
    sa.Column('query_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='الگوی جستجوی الستیک\u200cسرچ با پارامترهای متغیر'),
    sa.Column('available_indices', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='لیست ایندکس\u200cهای قابل جستجو'),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='الگوی تبدیل پاسخ الستیک\u200cسرچ'),
    sa.Column('error_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='الگوهای پاسخ برای خطاهای مختلف'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_types_name'), 'request_types', ['name'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('progress', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('incoming_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type_id', sa.UUID(), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elasticsearch_query', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_worker', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_requests_import_batch_id'), 'incoming_requests', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_incoming_requests_original_request_id'), 'incoming_requests', ['original_request_id'], unique=True)
    op.create_index(op.f('ix_incoming_requests_status'), 'incoming_requests', ['status'], unique=False)
    op.create_table('request_type_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameter_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('original_request_id', sa.UUID(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('elasticsearch_took_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_batch_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['incoming_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_results_export_batch_id'), 'query_results', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_query_results_original_request_id'), 'query_results', ['original_request_id'], unique=False)
    op.create_index(op.f('ix_query_results_request_id'), 'query_results', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_results_request_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_original_request_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_export_batch_id'), table_name='query_results')
    op.drop_table('query_results')
    op.drop_table('request_type_parameters')
    op.drop_index(op.f('ix_incoming_requests_status'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_original_request_id'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_import_batch_id'), table_name='incoming_requests')
    op.drop_table('incoming_requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_request_types_name'), table_name='request_types')
    op.drop_table('request_types')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_checksum'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_batch_type'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('exportable_settings')
    op.drop_index(op.f('ix_export_batches_status'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_checksum'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_batch_type'), table_name='export_batches')
    op.drop_table('export_batches')
    # ### end Alembic commands ###