"""Create ProfileTypeConfig table

Revision ID: 3b6200865448
Revises: 9d3726e488f1
Create Date: 2025-11-11 00:46:28.646672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6200865448'
down_revision: Union[str, None] = '9d3726e488f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_type_configs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('daily_request_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_request_limit', sa.Integer(), nullable=False),
    sa.Column('max_results_per_request', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('config_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_profile_type_configs_is_active'), 'profile_type_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_profile_type_configs_name'), 'profile_type_configs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_type_configs_name'), table_name='profile_type_configs')
    op.drop_index(op.f('ix_profile_type_configs_is_active'), table_name='profile_type_configs')
    op.drop_table('profile_type_configs')
    # ### end Alembic commands ###
