"""Add rate limits to ProfileTypeConfig

Revision ID: 69e610a39539
Revises: 3b6200865448
Create Date: 2025-11-13 02:57:01.819732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e610a39539'
down_revision: Union[str, None] = '3b6200865448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_type_configs', sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False))
    op.add_column('profile_type_configs', sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False))
    op.drop_column('profile_type_configs', 'max_results_per_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_type_configs', sa.Column('max_results_per_request', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('profile_type_configs', 'rate_limit_per_hour')
    op.drop_column('profile_type_configs', 'rate_limit_per_minute')
    # ### end Alembic commands ###
