"""Create all tables for response network

Revision ID: 7d8dac9026fe
Revises: 86b63da76484
Create Date: 2025-10-14 11:35:21.674682+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d8dac9026fe'
down_revision: Union[str, None] = '86b63da76484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_requests',
    sa.Column('original_request_id', sa.UUID(), nullable=False),
    sa.Column('original_user_id', sa.UUID(), nullable=False),
    sa.Column('query_type', sa.String(length=100), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_requests_original_request_id'), 'incoming_requests', ['original_request_id'], unique=True)
    op.create_index(op.f('ix_incoming_requests_original_user_id'), 'incoming_requests', ['original_user_id'], unique=False)
    op.create_index(op.f('ix_incoming_requests_priority'), 'incoming_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_incoming_requests_query_type'), 'incoming_requests', ['query_type'], unique=False)
    op.create_index(op.f('ix_incoming_requests_status'), 'incoming_requests', ['status'], unique=False)
    op.create_table('query_results',
    sa.Column('incoming_request_id', sa.UUID(), nullable=False),
    sa.Column('original_request_id', sa.UUID(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incoming_request_id'], ['incoming_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_results_export_batch_id'), 'query_results', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_query_results_incoming_request_id'), 'query_results', ['incoming_request_id'], unique=True)
    op.create_index(op.f('ix_query_results_original_request_id'), 'query_results', ['original_request_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_users_active', table_name='users')
    op.drop_index('ix_users_profile', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_profile_type'), 'users', ['profile_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile_type'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_profile', 'users', ['profile_type'], unique=False)
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_query_results_original_request_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_incoming_request_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_export_batch_id'), table_name='query_results')
    op.drop_table('query_results')
    op.drop_index(op.f('ix_incoming_requests_status'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_query_type'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_priority'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_original_user_id'), table_name='incoming_requests')
    op.drop_index(op.f('ix_incoming_requests_original_request_id'), table_name='incoming_requests')
    op.drop_table('incoming_requests')
    # ### end Alembic commands ###