"""add_requests_table

Revision ID: 8168fa1dc3ec
Revises: 4b993415583e
Create Date: 2025-11-02 03:05:48.345698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8168fa1dc3ec'
down_revision: Union[str, None] = '4b993415583e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('query_type', sa.String(length=50), nullable=False),
        sa.Column('query_params', sa.JSON(), nullable=False),
        sa.Column('elasticsearch_query', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('export_batch_id', sa.UUID(), nullable=True),
        sa.Column('result_received_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_export_batch_id'), 'requests', ['export_batch_id'], unique=False)
    op.create_index(op.f('ix_requests_exported_at'), 'requests', ['exported_at'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_exported_at'), table_name='requests')
    op.drop_index(op.f('ix_requests_export_batch_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###