"""ایجاد جدول کاربران به عنوان منبع حقیقت

Revision ID: 86b63da76484
Revises: 
Create Date: 2025-10-12 09:01:42.494750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b63da76484'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_type', sa.String(length=50), server_default='basic', nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default='10', nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), server_default='100', nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), server_default='500', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.CheckConstraint("profile_type IN ('basic', 'premium', 'enterprise', 'admin')"),
    sa.CheckConstraint("priority >= 1 AND priority <= 10")
    )
    op.create_index(op.f('ix_users_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_profile'), 'users', ['profile_type'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_profile'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###