"""add_processing_time_to_requests

Revision ID: 8e10faa8bdce
Revises: 8168fa1dc3ec
Create Date: 2025-11-02 03:09:10.028123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e10faa8bdce'
down_revision: Union[str, None] = '8168fa1dc3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('processing_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'processing_time')
    # ### end Alembic commands ###