"""Add ProfileTypeConfig model

Revision ID: 9d3726e488f1
Revises: ca43be690bcd
Create Date: 2025-11-11 00:45:51.978893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d3726e488f1'
down_revision: Union[str, None] = 'ca43be690bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request_access', sa.Column('max_requests_per_hour', sa.Integer(), nullable=False))
    op.drop_constraint('uix_user_request_type', 'user_request_access', type_='unique')
    op.drop_column('user_request_access', 'allowed_indices')
    op.drop_column('user_request_access', 'access_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request_access', sa.Column('access_type', postgresql.ENUM('READ', 'WRITE', 'ADMIN', name='accesstype'), autoincrement=False, nullable=False))
    op.add_column('user_request_access', sa.Column('allowed_indices', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.create_unique_constraint('uix_user_request_type', 'user_request_access', ['user_id', 'request_type_id'])
    op.drop_column('user_request_access', 'max_requests_per_hour')
    # ### end Alembic commands ###
