"""add profile_type to user

Revision ID: cc5053b1bbb0
Revises: 5415c9300ae2
Create Date: 2024-03-19 12:34:56.789012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5053b1bbb0'
down_revision: Union[str, None] = '5415c9300ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add profile_type column as nullable
    op.add_column('users', sa.Column('profile_type', sa.String(length=50), nullable=True))
    
    # 2. Update existing rows with default values
    op.execute("""
        UPDATE users 
        SET profile_type = CASE 
            WHEN username = 'admin' THEN 'admin'
            WHEN username = 'premium_user' THEN 'premium'
            ELSE 'basic'
        END
    """)
    
    # 3. Make profile_type non-nullable with a default value
    op.alter_column('users', 'profile_type',
                    existing_type=sa.String(length=50),
                    nullable=False,
                    server_default=sa.text("'basic'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_type')
    # ### end Alembic commands ###