"""Add allowed_indices to users table

Revision ID: dc792be45738
Revises: 7d8dac9026fe
Create Date: 2025-10-15 05:02:04.525738+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc792be45738'
down_revision: Union[str, None] = '7d8dac9026fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_indices', postgresql.JSONB(astext_type=sa.Text()), server_default='["products"]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_indices')
    # ### end Alembic commands ###