"""Create export_batches table

Revision ID: 627f4073f13b
Revises: c492acc35885
Create Date: 2025-10-13 10:38:13.496727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '627f4073f13b'
down_revision: Union[str, None] = 'c492acc35885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_export_batches_batch_type'), 'export_batches', ['batch_type'], unique=False)
    op.create_index(op.f('ix_export_batches_created_at'), 'export_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_batches_status'), 'export_batches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_batches_status'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_created_at'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_batch_type'), table_name='export_batches')
    op.drop_table('export_batches')
    # ### end Alembic commands ###
