"""add_processing_time_to_requests

Revision ID: b4c3c4a64e50
Revises: 3cc88ff34454
Create Date: 2025-11-02 11:10:20.029398+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c3c4a64e50'
down_revision: Union[str, None] = '3cc88ff34454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('processing_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'processing_time')
    # ### end Alembic commands ###
