"""Create responses table and add relationship to requests

Revision ID: c492acc35885
Revises: df9fcdfdadcb
Create Date: 2025-10-13 10:30:11.690180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c492acc35885'
down_revision: Union[str, None] = 'df9fcdfdadcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_cache_key'), 'responses', ['cache_key'], unique=False)
    op.create_index(op.f('ix_responses_import_batch_id'), 'responses', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_responses_request_id'), 'responses', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_request_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_import_batch_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_cache_key'), table_name='responses')
    op.drop_table('responses')
    # ### end Alembic commands ###
