"""Add ExportBatch and ImportBatch models

Revision ID: 834b80e14f5a
Revises: 703c9595dd29
Create Date: 2025-11-06 02:51:37.765613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834b80e14f5a'
down_revision: Union[str, None] = '703c9595dd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###